services:
    web:
        build: .
        image: portfoliofy
        ports:
            - "8000:8000"
        env_file:
            - .env
        command: python manage.py runserver 0.0.0.0:8000
        develop:
            watch:
                - action: sync
                  path: .
                  target: /app
