# Generated by Django 5.0 on 2024-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blogcontent_blog_post_postcontent_delete_blog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
