# Generated by Django 5.0 on 2024-11-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcontent",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post/content/"),
        ),
    ]
